@urlDev=http://localhost:1999
@name=transaction
@vesion=v.0.0.0

### GET_LIST
GET {{urlDev}}/api/user_bcoin
version: {{vesion}}

### POST
POST {{urlDev}}/api/user_bcoin
Content-Type: application/json

{
    "name": "nampdb",
    "password":"123456789",
    "pritaveKey":"",
    "publicKey":"",
    "extends":""
}

### LOGIN
POST {{urlDev}}/api/user_bcoin/login
Content-Type: application/json

{
    "name": "nampdb",
    "password":"123456789"
}

### DELETE 
DELETE {{urlDev}}/api/user_bcoin/63e710a9bccce118841c5b49
Content-Type: application/json
version: {{vesion}}


### POST
POST {{urlDev}}/api/blockchain
Content-Type: application/json

{
    "nonce": "1",
    "hash":"1",
    "previousHash":"2",
    "transactions":"2",
    "timestamp":"2"
}

### GET
GET {{urlDev}}/api/blockchain
Content-Type: application/json